apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.claimName }}
    labels:
       type: local
spec:
   storageClassName: {{ .Values.storageClass }}
   accessModes:
   - {{ .Values.accessModes }}
   resources:
     requests:
       storage: {{ .Values.pvcStorage }}